#include "menu.h"



void help() {
    std::cout << "=========Использование программы========" << std::endl;
    std::cout << "./main -f <filename> -q \"команда\"" << std::endl;
    std::cout << "=================Ключи==================" << std::endl;
    std::cout << "-h, --help          показать эту справку" << std::endl;
    std::cout << "-f, --file <arg>    использование файла arg" << std::endl;
    std::cout << "-q, --query <arg>   выполнение команды arg" << std::endl;
    std::cout << std::endl;
    std::cout << "============Создание структур===========" << std::endl;
    std::cout << "MCREATE <name>              создать массив" << std::endl;
    std::cout << "FCREATE <name>              создать односвязный список" << std::endl;
    std::cout << "DCREATE <name>              создать двусвязный список" << std::endl;
    std::cout << "SCREATE <name>              создать стек" << std::endl;
    std::cout << "QCREATE <name>              создать очередь" << std::endl;
    std::cout << "TABLEOPENCREATE <name>      создать хэш таблицу открытой адресации" << std::endl;
    std::cout << "TABLECHAINCREATE <name>     создать хэш таблицу методом цепочек" << std::endl;
    std::cout << "TCREATE <name>              создать АВЛ дерево" << std::endl;
    std::cout << std::endl;
    std::cout << "==========Операции с массивом==========" << std::endl;
    std::cout << "MPUSH <name> <value>              добавить в конец" << std::endl;
    std::cout << "MPUSHINDEX <name> <index> <value> добавить в индекс" << std::endl;
    std::cout << "MGET <name> <index>               получение значения по индексу" << std::endl;
    std::cout << "MDELINDEX <name> <index>          удаление по индексу" << std::endl;
    std::cout << "MREPLACE <name> <index> <value>   замена по индексу" << std::endl;
    std::cout << "MLEN <name>                       получить длину массива" << std::endl;
    std::cout << std::endl;
    std::cout << "=====Операции с односвязным списком====" << std::endl;
    std::cout << "FPUSHHEAD <name> <value>          добавить в начало" << std::endl;
    std::cout << "FPUSHTAIL <name> <value>          добавить в конец" << std::endl;
    std::cout << "FPUSHAFTER <name> <index> <value> добавить после индекса" << std::endl;
    std::cout << "FPUSHBEFORE <name> <index> <value> добавить до индекса" << std::endl;
    std::cout << "FDELHEAD <name>                   удалить из начала" << std::endl;
    std::cout << "FDELTAIL <name>                   удалить из конца" << std::endl;
    std::cout << "FDELAFTER <name> <index>          удалить после индекса" << std::endl;
    std::cout << "FDELBEFORE <name> <index>         удалить до индекса" << std::endl;
    std::cout << "FDELVALUE <name> <value>          удалить по значению" << std::endl;
    std::cout << "FSEARCH <name> <value>            найти элемент" << std::endl;
    std::cout << std::endl;
    std::cout << "=====Операции с двусвязным списком=====" << std::endl;
    std::cout << "DPUSHHEAD <name> <value>          добавить в начало" << std::endl;
    std::cout << "DPUSHTAIL <name> <value>          добавить в конец" << std::endl;
    std::cout << "DPUSHAFTER <name> <index> <value> добавить после индекса" << std::endl;
    std::cout << "DPUSHBEFORE <name> <index> <value> добавить до индекса" << std::endl;
    std::cout << "DDELHEAD <name>                   удалить из начала" << std::endl;
    std::cout << "DDELTAIL <name>                   удалить из конца" << std::endl;
    std::cout << "DDELAFTER <name> <index>          удалить после индекса" << std::endl;
    std::cout << "DDELBEFORE <name> <index>         удалить до индекса" << std::endl;
    std::cout << "DDELVALUE <name> <value>          удалить по значению" << std::endl;
    std::cout << "DSEARCH <name> <value>            найти элемент" << std::endl;
    std::cout << std::endl;
    std::cout << "=========Операции со стеком============" << std::endl;
    std::cout << "SPUSH <name> <value>              добавить" << std::endl;
    std::cout << "SPOP <name>                       удалить и получить" << std::endl;
    std::cout << std::endl;
    std::cout << "=========Операции с очередью===========" << std::endl;
    std::cout << "QPUSH <name> <value>              добавить" << std::endl;
    std::cout << "QPOP <name>                       удалить и получить" << std::endl;
    std::cout << std::endl;
    std::cout << "===Хэш таблица (открытая адресация)====" << std::endl;
    std::cout << "TABLEOPENADD <name> <key> <value> добавить элемент" << std::endl;
    std::cout << "TABLEOPENDEL <name> <key>         удалить элемент" << std::endl;
    std::cout << "TABLEOPENGET <name> <key>         найти элемент" << std::endl;
    std::cout << std::endl;
    std::cout << "=====Хэш таблица (метод цепочек)======" << std::endl;
    std::cout << "TABLECHAINADD <name> <key> <value> добавить элемент" << std::endl;
    std::cout << "TABLECHAINDEL <name> <key>         удалить элемент" << std::endl;
    std::cout << "TABLECHAINGET <name> <key>         найти элемент" << std::endl;
    std::cout << std::endl;
    std::cout << "========Операции с АВЛ деревом=========" << std::endl;
    std::cout << "TPUSH <name> <value>               добавить элемент" << std::endl;
    std::cout << "TDEL <name> <value>                удалить элемент" << std::endl;
    std::cout << "TSEARCH <name> <value>             найти элемент" << std::endl;
    std::cout << std::endl;
    std::cout << "============Общие команды=============" << std::endl;
    std::cout << "PRINT <name>                       вывести структуру" << std::endl;
    std::cout << std::endl;
    std::cout << "=============Примеры==================" << std::endl;
    std::cout << "./main -f data.txt -q \"MCREATE arr1\"" << std::endl;
    std::cout << "./main -f data.txt -q \"MPUSH arr1 hello\"" << std::endl;
    std::cout << "./main -f data.txt -q \"PRINT arr1\"" << std::endl;
    std::cout << "./main -f data.txt -q \"FCREATE list1; FPUSHHEAD list1 world; PRINT list1\"" << std::endl;
}
